# Generated by Django 4.0.5 on 2022-06-09 00:10

from django.db import migrations, models
import django.db.models.deletion
import django_mysql.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_full_name', models.CharField(max_length=255)),
                ('user_age', models.IntegerField()),
                ('user_email', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Recipes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipe_name', models.CharField(max_length=255)),
                ('creation_date', models.DateField()),
                ('recipe_ingredients', django_mysql.models.ListTextField(models.CharField(max_length=255), size=None)),
                ('recipe_instructions', models.TextField(help_text='Por favor escriba a detalle los pasos para la receta')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipes_app.usermodel')),
            ],
        ),
        migrations.CreateModel(
            name='Avatar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatar')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipes_app.usermodel')),
            ],
        ),
    ]
