# Generated by Django 4.0.5 on 2022-06-09 03:34

from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipes',
            name='recipe_ingredients',
            field=django_mysql.models.ListTextField(models.CharField(max_length=10000000), size=None),
        ),
    ]
