# Generated by Django 4.0.5 on 2022-06-09 03:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes_app', '0002_alter_recipes_recipe_ingredients'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Avatar',
        ),
    ]
